{% set name = "intake-esm" %}
{% set version = "2019.4.26" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ced11b72ece08e3f1d219f6cc1bc15a6c4e1fb6157897387c6ed8ff9fd44d923
  

build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  noarch: python

requirements:

  host:
    - python >3.5
    - pip

  run:
    - python >3.5
    - xarray
    - intake-xarray
    - dask

test:
  source_files:
    - tests
  requires:
    - pytest
    - xarray
    - netcdf4
  imports:
    - intake_esm
  commands:
    - pytest tests/test_cmip.py -v 
    - pytest tests/test_config.py -v 

about:
  
  home: https://github.com/NCAR/intake-esm
  license: Apache 2.0
  summary: |
    Intake-esm provides a plugin for building and loading intake catalogs for earth system data sets holdings, such as CMIP and CESM Large Ensemble datasets.  
  dev_url: https://github.com/NCAR/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
