{% set name = "intake-esm" %}
{% set version = "2021.1.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6cd1aaecc1df68f0a7b94ab405db347b9592354a7b29b037dc8935f74ee09a1b

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:

  host:
    - python >=3.7
    - pip
    - setuptools_scm

  run:
    - python >=3.7
    - dask
    - fastprogress >=0.2.6
    - fsspec >=0.8.0
    - h5netcdf >=0.8.1
    - intake >=0.6.0
    - netcdf4 >=1.5.5
    - requests >=2.24.0
    - xarray >=0.16.2
    - zarr >=2.5


test:
  imports:
    - intake_esm

about:
  home: https://github.com/intake/intake-esm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An intake plugin for Earth System Model (ESM) data sets holdings.
  description: |
    An intake plugin for parsing an Earth System Model (ESM) collection/catalog and 
    loading assets (netCDF files and/or Zarr stores) into xarray data sets.
  dev_url: https://github.com/intake/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
    - sherimickelson
