{% set name = "intake-esm" %}
{% set version = "2020.12.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3d3ad948ae361443d53f13a6533e5970137ff9c56d74faa0fd3c7c110b89af0

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:

  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - dask
    - fastprogress >=0.2.6
    - fsspec >=0.8.0
    - h5netcdf >=0.8.1
    - intake >=0.6.0
    - netcdf4 >=1.5.3
    - requests >=2.24.0
    - xarray >=0.16
    - zarr >=2.4


test:
  imports:
    - intake_esm

about:
  home: https://github.com/intake/intake-esm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An intake plugin for Earth System Model (ESM) data sets holdings.
  description: |
    An intake plugin for parsing an Earth System Model (ESM) collection/catalog and 
    loading assets (netCDF files and/or Zarr stores) into xarray data sets.
  dev_url: https://github.com/intake/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
    - sherimickelson
