{% set python_min = "3.10" %}
{% set name = "intake-esm" %}
{% set version = "2025.7.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d82a61e13c11a01a6c50cfebc885bb4c41fc943d907b70a131cef32734458c8b

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:

  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm

  run:
    - itables
    - dask-core >=2024.12
    - python >={{ python_min }}
    - dask >=2024.12
    - fastprogress >=1.0.0
    - fsspec >=2024.12
    - intake >=2.0.0
    - netcdf4 >=1.5.5
    - requests >=2.24.0
    - xarray >=2024.10
    - zarr >=2.12
    - pydantic >=2.0
    - pydap !=3.5.5
    - pandas >=2.1.0
    - polars >=1.24.0


test:
  imports:
    - intake_esm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intake/intake-esm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An intake plugin for Earth System Model (ESM) data sets holdings.
  description: |
    An intake plugin for parsing an Earth System Model (ESM) collection/catalog and 
    loading assets (netCDF files and/or Zarr stores) into xarray data sets.
  dev_url: https://github.com/intake/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
    - sherimickelson
    - mgrover1
    - charles-turner-1
