{% set name = "intake-esm" %}
{% set version = "2020.5.21" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e50f0e094c0799c07ba65e31b1cb88793f2c22a3e075858a7ead7208a26abaaa

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python

requirements:

  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - dask
    - fsspec
    - intake >=0.5.2
    - requests
    - xarray >=0.15
    - tqdm


test:
  imports:
    - intake_esm

about:
  home: https://github.com/NCAR/intake-esm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An intake plugin for earth system model data sets holdings
  description: |
    An intake plugin for parsing an ESM (Earth System Model) Collection/catalog and 
    loading assets (netCDF files and/or Zarr stores) into xarray data sets.
  dev_url: https://github.com/NCAR/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
