{% set name = "intake-esm" %}
{% set version = "2023.11.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b8f1b2368eebfaf00121886dfc8e59410dd2151c3bee205d09d2bec3df413a4

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:

  host:
    - python >=3.9
    - pip
    - setuptools_scm

  run:
    - python >=3.9
    - dask >=2022.02.0
    - fastprogress >=1.0.0
    - fsspec >=2022.11.0
    - intake >=0.6.6
    - netcdf4 >=1.5.5
    - requests >=2.24.0
    - xarray >=2022.06
    - zarr >=2.12
    - pydantic >=2.0
    - pandas>=2.1.0


test:
  imports:
    - intake_esm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-esm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An intake plugin for Earth System Model (ESM) data sets holdings.
  description: |
    An intake plugin for parsing an Earth System Model (ESM) collection/catalog and 
    loading assets (netCDF files and/or Zarr stores) into xarray data sets.
  dev_url: https://github.com/intake/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
    - sherimickelson
    - mgrover1
